### ISSUE TITLE
open DSN querys

### ISSUE THREAD

**Issue by y0d4a** [aelth/ddospot#4]
Hi, how i can see which IP made request from the log?

> DNSPot started at 0.0.0.0:53
> {"src_ip": "172.26.0.1", "src_port": 38819, "opcode": 0, "dns_name": "clients4.google.com", "dns_type": "A", "dns_cls": "IN", "time": "2024-03-13 07:22:28.837122"}
> {"src_ip": "172.26.0.1", "src_port": 7613, "opcode": 0, "dns_name": "clients4.google.com", "dns_type": "UNKNOWN (65)", "dns_cls": "IN", "time": "2024-03-13 07:22:28.855682"}
> Flushing information for 2 (IP, dns, type, class) quartets to database...
> New attack started for quartet ('172.26.0.1', 'clients4.google.com', 'A', 'IN')
> {"src_ip": "172.26.0.1", "src_port": 39631, "opcode": 0, "dns_name": "clients4.google.com", "dns_type": "A", "dns_cls": "IN", "time": "2024-03-13 07:53:52.358883"}
> New attack started for quartet ('172.26.0.1', 'clients4.google.com', 'UNKNOWN (65)', 'IN')
> {"src_ip": "172.26.0.1", "src_port": 65504, "opcode": 0, "dns_name": "clients4.google.com", "dns_type": "UNKNOWN (65)", "dns_cls": "IN", "time": "2024-03-13 07:53:52.372677"}
> Flushing information for 2 (IP, dns, type, class) quartets to database...
> Full blacklist written: 2 scanners/attackers detected
> Weekly blacklist written: 1 scanners/attackers detected
> Daily blacklist written: 1 scanners/attackers detected
> {"src_ip": "172.26.0.1", "src_port": 59662, "opcode": 0, "dns_name": "eu-lurker-input.gravityzone.bitdefender.com", "dns_type": "A", "dns_cls": "IN", "time": "2024-03-13 14:13:07.977472"}
> New attack started for quartet ('172.26.0.1', 'eu-lurker-input.gravityzone.bitdefender.com', 'AAAA', 'IN')
> {"src_ip": "172.26.0.1", "src_port": 59662, "opcode": 0, "dns_name": "eu-lurker-input.gravityzone.bitdefender.com", "dns_type": "AAAA", "dns_cls": "IN", "time": "2024-03-13 14:13:08.059641"}
> Threshold reached for quartet ('172.26.0.1', 'eu-lurker-input.gravityzone.bitdefender.com', 'A', 'IN') - will not respond to this host/query tuple
> Threshold reached for quartet ('172.26.0.1', 'eu-lurker-input.gravityzone.bitdefender.com', 'AAAA', 'IN') - will not respond to this host/query tuple
> Flushing information for 2 (IP, dns, type, class) quartets to database...

**Comment by aelth** [comment]
I assume you're running the ddospot in Docker and you're seeing only Docker IP.

**Comment by y0d4a** [comment]
yeap
